// ==UserScript==
// @name         Erev HomePage Improvements
// @include      *www.erevollution.com/*/index
// @version      0.0.7
// @description  Erev HomePage Improvements
// @author       Anonymous
// @grant        none
// ==/UserScript==

function style(a){$("head").append("<style>"+a+"</style>")}!function(){"use strict";style(".hits {color: #595959;}");navigator.language||navigator.userLanguage||"en-US";$(document).ready(function(){function c(){var a=$("ul.nav-pills > li").eq(6);if(void 0===a)return False;var b=a.find("a");b.addClass("dropdown-toggle").append('<i class="fa fa-angle-right drop-icon"></i>'),a.append('<ul class="submenu"><li><a href="'+b.attr("href")+'">'+b.find("span").html()+'</a></li><li><a href="'+b.attr("href")+'#tab-2">Referrals</a></li></ul>'),$('.nav-tabs a[href="'+location.hash+'"]').tab("show")}function g(){var a=$("table.table"),b=a.find("tbody tr"),d=b.length;b.each(function(a,b){if(a==d-1&&e.length>0)return!1;var c=$(this),g=i(c.find("td:gt(0) > a").attr("href"));f.donated[g]=f.donated[g]||0,f.donated[g]+=parseFloat(c.find("td:eq(3) > strong").html())}),localStorage.setItem("erevRD",JSON.stringify(f))}function h(a){if("#tab-2"!=a)return!1;var b=$("table.table");b.find("thead > tr").append('<th class="text-center">Already Collected</th>');var c=b.find("tbody tr"),d=c.length;c.each(function(a,b){var c=$(this);if(a==d-1&&e.length>0)return c.find("td:eq(0)").attr("colspan",4),!1;var g=i(c.find("td:gt(0) > a").attr("href"));c.append('<td class="text-center"><strong>'+(f.donated[g]&&f.donated[g].toLocaleString())+"</strong></td>")}),localStorage.setItem("erevRD",JSON.stringify(f))}function i(a){if(void 0===a)return 0;var b=a.split("/");return b[b.length-1]}function j(){var c=$("div#energyBarT");if(void 0===c)return False;var d=parseFloat(c.html().split("/")[0]),e=parseFloat(c.html().split("/")[1]);if(d<e){k();var f=l();a>=f&&$("#energyButton").trigger("click")}else void 0!==b&&clearInterval(b)}function k(){a=parseFloat($("strong#energyButtonT").html())}function l(){return 10*Math.ceil(10*Math.random())}var a=0,b=setInterval(j,36e4);setTimeout(j,5e3),c();var e,d="",f=JSON.parse(localStorage.getItem("erevRD"))||{};$('a[data-toggle="tab"]').on("shown.bs.tab",function(a){d=$(a.target).attr("href"),"#tab-2"==d&&(e=$("table.table").find("tbody tr").last().find("form"),e.length>0&&e.submit(function(a){g()})),h(d)})})}();
