// ==UserScript==
// @name         Erev HomePage Improvements
// @include      *www.erevollution.com/*/index
// @version      0.0.9
// @description  Erev HomePage Improvements
// @author       Anonymous
// @grant        none
// ==/UserScript==

function style(a){$("head").append("<style>"+a+"</style>")}!function(){"use strict";style(".hits {color: #595959;}"),style(".dropdown:hover .dropdown-menu {display: block;}");var b=(navigator.language||navigator.userLanguage||"en-US","#tab-2"),c="special-items";$(document).ready(function(){function f(){var a=$("ul.nav-pills > li").eq(6);if(void 0===a)return False;var b=a.find("a");b.addClass("dropdown-toggle").append('<i class="fa fa-angle-right drop-icon"></i>'),a.append('<ul class="submenu"><li><a href="'+b.attr("href")+'">'+b.find("span").html()+'</a></li><li><a href="'+b.attr("href")+'#tab-2">Referrals</a></li></ul>'),$('.nav-tabs a[href="'+location.hash+'"]').tab("show")}function j(){var a=$("table.table"),b=a.find("tbody tr"),d=b.length;b.each(function(a,b){if(a==d-1&&h.length>0)return!1;var c=$(this),e=l(c.find("td:gt(0) > a").attr("href"));i.donated[e]=i.donated[e]||0,i.donated[e]+=parseFloat(c.find("td:eq(3) > strong").html())}),localStorage.setItem("erevRD",JSON.stringify(i))}function k(){var a=$("table.table");a.find("thead > tr").append('<th class="text-center">Already Collected</th>');var b=a.find("tbody tr"),c=b.length;b.each(function(a,b){var d=$(this);if(a==c-1&&h.length>0)return d.find("td:eq(0)").attr("colspan",4),!1;var e=l(d.find("td:gt(0) > a").attr("href"));d.append('<td class="text-center"><strong>'+(i.donated[e]&&i.donated[e].toLocaleString())+"</strong></td>")})}function l(a){if(void 0===a)return 0;var b=a.split("/");return b[b.length-1]}function m(){console.log((new Date).toUTCString());var b=$("div#energyBarT");if(void 0===b)return False;var c=parseFloat(b.html().split("/")[0]),f=parseFloat(b.html().split("/")[1]);if(c<f){n();var g=10*o();a>=g&&(console.log(d*d*1.13*1e3),setTimeout(function(){$("#energyButton").trigger("click")},d*d*1.13*1e3))}else void 0!==e&&clearInterval(e)}function n(){a=parseFloat($("strong#energyButtonT").html())}function o(){return d=Math.ceil(10*Math.random())}var a=0,d=6,e=setInterval(m,6e4*d);setTimeout(m,3e3),f();var h,g="",i=JSON.parse(localStorage.getItem("erevRD"))||{};$('a[data-toggle="tab"]').on("shown.bs.tab",function(a){g=$(a.target).attr("href"),g==b&&location.pathname.indexOf(c)>=0&&(h=$("table.table").find("tbody tr").last().find("form"),h.length>0&&h.submit(function(a){j()}),k())})})}();
